kind: pipeline
name: docker

trigger:
  branch:
    - main

clone:
  disable: true

steps:
  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: scripts-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      TARGET_ARCH: amd64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp -r etc dist/linux-$TARGET_ARCH/
      - cp -r scripts dist/linux-$TARGET_ARCH/
      - cp -r service dist/linux-$TARGET_ARCH/
    depends_on:
      - fetch

  - name: runc-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/runc:v1.1.14-amd64
    environment:
      TARGET_ARCH: amd64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/runc dist/linux-$TARGET_ARCH/

  - name: containerd-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/containerd:v2.0.0-rc.4-amd64
    environment:
      TARGET_ARCH: amd64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/container* dist/linux-$TARGET_ARCH/
      - cp /usr/local/bin/ctr dist/linux-$TARGET_ARCH/
      - cp /usr/local/bin/nerdctl dist/linux-$TARGET_ARCH/nerdctl

  - name: dockerd-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/dockerd:v27.3.1-amd64
    environment:
      TARGET_ARCH: amd64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/docker* dist/linux-$TARGET_ARCH/

  - name: cni-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/kube-cni-plugins:v1.3.0-amd64
    environment:
      TARGET_ARCH: amd64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH/cni-plugins
      - cp /opt/cni/bin/* dist/linux-$TARGET_ARCH/cni-plugins/

  - name: iptables-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/iptables:v1.8.0-amd64
    environment:
      TARGET_ARCH: amd64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp -r /iptables dist/linux-$TARGET_ARCH

  - name: tgz-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      TARGET_ARCH: amd64
    commands:
      - mkdir -p .tmp/$TARGET_ARCH
      - tar zcvf .tmp/$TARGET_ARCH/docker-27.3.1.tgz docker -C dist/linux-$TARGET_ARCH/ .
    depends_on:
      - scripts-amd64
      - runc-amd64
      - containerd-amd64
      - dockerd-amd64
      - cni-amd64
      - iptables-amd64

  - name: scripts-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      TARGET_ARCH: arm64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp -r etc dist/linux-$TARGET_ARCH/
      - cp -r scripts dist/linux-$TARGET_ARCH/
      - cp -r service dist/linux-$TARGET_ARCH/
    depends_on:
      - fetch

  - name: runc-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/runc:v1.1.14-arm64
    environment:
      TARGET_ARCH: arm64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/runc dist/linux-$TARGET_ARCH/

  - name: containerd-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/containerd:v2.0.0-rc.4-arm64
    environment:
      TARGET_ARCH: arm64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/container* dist/linux-$TARGET_ARCH/
      - cp /usr/local/bin/ctr dist/linux-$TARGET_ARCH/
      - cp /usr/local/bin/nerdctl dist/linux-$TARGET_ARCH/nerdctl

  - name: dockerd-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/dockerd:v27.3.1-arm64
    environment:
      TARGET_ARCH: arm64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/docker* dist/linux-$TARGET_ARCH/

  - name: cni-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/kube-cni-plugins:v1.3.0-arm64
    environment:
      TARGET_ARCH: arm64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH/cni-plugins
      - cp /opt/cni/bin/* dist/linux-$TARGET_ARCH/cni-plugins/

  - name: iptables-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/iptables:v1.8.0-arm64
    environment:
      TARGET_ARCH: arm64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp -r /iptables dist/linux-$TARGET_ARCH

  - name: tgz-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      TARGET_ARCH: arm64
    commands:
      - mkdir -p .tmp/$TARGET_ARCH
      - tar zcvf .tmp/$TARGET_ARCH/docker-27.3.1.tgz docker -C dist/linux-$TARGET_ARCH/ .
    depends_on:
      - scripts-arm64
      - runc-arm64
      - containerd-arm64
      - dockerd-arm64
      - cni-arm64
      - iptables-arm64

  - name: scripts-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      TARGET_ARCH: loong64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp -r etc dist/linux-$TARGET_ARCH/
      - cp -r scripts dist/linux-$TARGET_ARCH/
      - cp -r service dist/linux-$TARGET_ARCH/
    depends_on:
      - fetch

  - name: runc-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/runc:v1.1.14-loong64
    environment:
      TARGET_ARCH: loong64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/runc dist/linux-$TARGET_ARCH/

  - name: containerd-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/containerd:v2.0.0-rc.4-loong64
    environment:
      TARGET_ARCH: loong64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/container* dist/linux-$TARGET_ARCH/
      - cp /usr/local/bin/ctr dist/linux-$TARGET_ARCH/
      - cp /usr/local/bin/nerdctl dist/linux-$TARGET_ARCH/nerdctl

  - name: dockerd-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/dockerd:v27.3.1-loong64
    environment:
      TARGET_ARCH: loong64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp /usr/local/bin/docker* dist/linux-$TARGET_ARCH/

  - name: cni-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/kube-cni-plugins:v1.3.0-loong64
    environment:
      TARGET_ARCH: loong64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH/cni-plugins
      - cp /opt/cni/bin/* dist/linux-$TARGET_ARCH/cni-plugins/

  - name: iptables-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/iptables:v1.8.0-loong64
    environment:
      TARGET_ARCH: loong64
    commands:
      - mkdir -p dist/linux-$TARGET_ARCH
      - cp -r /iptables dist/linux-$TARGET_ARCH

  - name: tgz-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      TARGET_ARCH: loong64
    commands:
      - mkdir -p .tmp/$TARGET_ARCH
      - tar zcvf .tmp/$TARGET_ARCH/docker-27.3.1.tgz docker -C dist/linux-$TARGET_ARCH/ .
    depends_on:
      - scripts-loong64
      - runc-loong64
      - containerd-loong64
      - dockerd-loong64
      - cni-loong64
      - iptables-loong64

  - name: minio
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-minio:1.0
    environment:
      S3_ACCESS_KEY:
        from_secret: ACCESS_KEY_MINIO
      S3_SECRET_KEY:
        from_secret: SECRET_KEY_MINIO
    commands:
      - mkdir -p .tmp
      - mc alias set cache --api=S3v4 https://cache.wodcloud.com $S3_ACCESS_KEY $S3_SECRET_KEY
      - mc cp *.sh cache/kubernetes/k8s/docker/
      - mc cp --recursive .tmp/ cache/kubernetes/k8s/docker/
    depends_on:
      - fetch
      - tgz-amd64
      - tgz-arm64
      - tgz-loong64

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets
