kind: pipeline
name: docker

trigger:
  branch:
    - main

clone:
  disable: true

steps:
  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY
        
  - name: runc-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/runc:v1.1.4-amd64
    commands:
      - mkdir -p dist/linux-amd64
      - cp /usr/local/bin/runc dist/linux-amd64/

  - name: containerd-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/containerd:v1.6.18-amd64
    commands:
      - mkdir -p dist/linux-amd64
      - cp /usr/local/bin/ctr dist/linux-amd64/
      - cp /usr/local/bin/containerd dist/linux-amd64/
      - cp /usr/local/bin/containerd-shim dist/linux-amd64/
      - cp /usr/local/bin/containerd-shim-runc-v1 dist/linux-amd64/
      - cp /usr/local/bin/containerd-shim-runc-v2 dist/linux-amd64/
      - cp /usr/local/bin/containerd-stress dist/linux-amd64/

  - name: nerdctl-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/nerdctl:v1.2.0-amd64
    commands:
      - mkdir -p dist/linux-amd64
      - cp /usr/local/bin/nerdctl dist/linux-amd64/nerdctl

  - name: docker-init-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/tini:v0.19.0-amd64
    commands:
      - mkdir -p dist/linux-amd64
      - cp /usr/local/bin/tini-static dist/linux-amd64/docker-init

  - name: docker-cli-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-cli:v23.0.1-amd64
    commands:
      - mkdir -p dist/linux-amd64
      - cp /usr/local/bin/docker dist/linux-amd64/

  - name: dockerd-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/dockerd:v23.0.1-amd64
    commands:
      - mkdir -p dist/linux-amd64
      - cp /usr/local/bin/dockerd dist/linux-amd64/

  - name: tgz-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    commands:
      - mkdir -p .tmp/amd64
      - tar zcvf .tmp/amd64/docker-23.0.1.tgz docker -C dist/linux-amd64/ .
    depends_on:
      - runc-amd64
      - containerd-amd64
      - nerdctl-amd64
      - docker-init-amd64
      - docker-cli-amd64
      - dockerd-amd64

  - name: runc-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/runc:v1.1.4-arm64
    commands:
      - mkdir -p dist/linux-arm64
      - cp /usr/local/bin/runc dist/linux-arm64/

  - name: containerd-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/containerd:v1.6.18-arm64
    commands:
      - mkdir -p dist/linux-arm64
      - cp /usr/local/bin/ctr dist/linux-arm64/
      - cp /usr/local/bin/containerd dist/linux-arm64/
      - cp /usr/local/bin/containerd-shim dist/linux-arm64/
      - cp /usr/local/bin/containerd-shim-runc-v1 dist/linux-arm64/
      - cp /usr/local/bin/containerd-shim-runc-v2 dist/linux-arm64/
      - cp /usr/local/bin/containerd-stress dist/linux-arm64/

  - name: nerdctl-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/nerdctl:v1.2.0-arm64
    commands:
      - mkdir -p dist/linux-arm64
      - cp /usr/local/bin/nerdctl dist/linux-arm64/nerdctl

  - name: docker-init-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/tini:v0.19.0-arm64
    commands:
      - mkdir -p dist/linux-arm64
      - cp /usr/local/bin/tini-static dist/linux-arm64/docker-init

  - name: docker-cli-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-cli:v23.0.1-arm64
    commands:
      - mkdir -p dist/linux-arm64
      - cp /usr/local/bin/docker dist/linux-arm64/

  - name: dockerd-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/dockerd:v23.0.1-arm64
    commands:
      - mkdir -p dist/linux-arm64
      - cp /usr/local/bin/dockerd dist/linux-arm64/

  - name: tgz-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    commands:
      - mkdir -p .tmp/arm64
      - tar zcvf .tmp/arm64/docker-23.0.1.tgz docker -C dist/linux-arm64/ .
    depends_on:
      - runc-arm64
      - containerd-arm64
      - nerdctl-arm64
      - docker-init-arm64
      - docker-cli-arm64
      - dockerd-arm64

  - name: runc-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/runc:v1.1.4-ppc64le
    commands:
      - mkdir -p dist/linux-ppc64le
      - cp /usr/local/bin/runc dist/linux-ppc64le/

  - name: containerd-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/containerd:v1.6.18-ppc64le
    commands:
      - mkdir -p dist/linux-ppc64le
      - cp /usr/local/bin/ctr dist/linux-ppc64le/
      - cp /usr/local/bin/containerd dist/linux-ppc64le/
      - cp /usr/local/bin/containerd-shim dist/linux-ppc64le/
      - cp /usr/local/bin/containerd-shim-runc-v1 dist/linux-ppc64le/
      - cp /usr/local/bin/containerd-shim-runc-v2 dist/linux-ppc64le/
      - cp /usr/local/bin/containerd-stress dist/linux-ppc64le/

  - name: nerdctl-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/nerdctl:v1.2.0-ppc64le
    commands:
      - mkdir -p dist/linux-ppc64le
      - cp /usr/local/bin/nerdctl dist/linux-ppc64le/nerdctl

  - name: docker-init-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/tini:v0.19.0-ppc64le
    commands:
      - mkdir -p dist/linux-ppc64le
      - cp /usr/local/bin/tini-static dist/linux-ppc64le/docker-init

  - name: docker-cli-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-cli:v23.0.1-ppc64le
    commands:
      - mkdir -p dist/linux-ppc64le
      - cp /usr/local/bin/docker dist/linux-ppc64le/

  - name: dockerd-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/dockerd:v23.0.1-ppc64le
    commands:
      - mkdir -p dist/linux-ppc64le
      - cp /usr/local/bin/dockerd dist/linux-ppc64le/

  - name: tgz-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
    commands:
      - mkdir -p .tmp/ppc64le
      - tar zcvf .tmp/ppc64le/docker-23.0.1.tgz docker -C dist/linux-ppc64le/ .
    depends_on:
      - runc-ppc64le
      - containerd-ppc64le
      - nerdctl-ppc64le
      - docker-init-ppc64le
      - docker-cli-ppc64le
      - dockerd-ppc64le

  # - name: runc-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/runc:v1.1.4-mips64le
  #   commands:
  #     - mkdir -p dist/linux-mips64le
  #     - cp /usr/local/bin/runc dist/linux-mips64le/

  # - name: containerd-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/containerd:v1.6.18-mips64le
  #   commands:
  #     - mkdir -p dist/linux-mips64le
  #     - cp /usr/local/bin/ctr dist/linux-mips64le/
  #     - cp /usr/local/bin/containerd dist/linux-mips64le/
  #     - cp /usr/local/bin/containerd-shim dist/linux-mips64le/
  #     - cp /usr/local/bin/containerd-shim-runc-v1 dist/linux-mips64le/
  #     - cp /usr/local/bin/containerd-shim-runc-v2 dist/linux-mips64le/
  #     - cp /usr/local/bin/containerd-stress dist/linux-mips64le/

  # - name: nerdctl-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/nerdctl:v1.2.0-mips64le
  #   commands:
  #     - mkdir -p dist/linux-mips64le
  #     - cp /usr/local/bin/nerdctl dist/linux-mips64le/nerdctl

  # - name: docker-init-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/tini:v0.19.0-mips64le
  #   commands:
  #     - mkdir -p dist/linux-mips64le
  #     - cp /usr/local/bin/tini-static dist/linux-mips64le/docker-init

  # - name: docker-cli-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/docker-cli:v23.0.1-mips64le
  #   commands:
  #     - mkdir -p dist/linux-mips64le
  #     - cp /usr/local/bin/docker dist/linux-mips64le/

  # - name: dockerd-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/dockerd:v23.0.1-mips64le
  #   commands:
  #     - mkdir -p dist/linux-mips64le
  #     - cp /usr/local/bin/dockerd dist/linux-mips64le/

  # - name: tgz-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
  #   commands:
  #     - mkdir -p .tmp/mips64le
  #     - tar zcvf .tmp/mips64le/docker-23.0.1.tgz docker -C dist/linux-mips64le/ .
  #   depends_on:
  #     - runc-mips64le
  #     - containerd-mips64le
  #     - nerdctl-mips64le
  #     - docker-init-mips64le
  #     - docker-cli-mips64le
  #     - dockerd-mips64le

  - name: minio
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-minio:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      S3_ACCESS_KEY: 
        from_secret: ACCESS_KEY_MINIO
      S3_SECRET_KEY: 
        from_secret: SECRET_KEY_MINIO
    commands:
      - mkdir -p .tmp
      - cp -r ./scripts/*.sh .tmp
      - mc alias set cache --api=S3v4 https://cache.wodcloud.com $S3_ACCESS_KEY $S3_SECRET_KEY
      - mc cp --recursive .tmp/ cache/kubernetes/k8s/docker/
    depends_on:
      - fetch
      - tgz-amd64
      - tgz-arm64
      - tgz-ppc64le
      # - tgz-mips64le

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets
  
---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets
